### PR TITLE
Fixing ruby file to work with latest homebrew

### PR DESCRIPTION
**Pull request by rajatkumar**
Minor fix to ensure general stack setup can happen for new installations. Please review @vinluvie @kelvl .

### CODE REVIEW

**Comment by vinluvie** [comment]
tried on your laptop and worked with the fix?

**Comment by rajatkumar** [comment]
Yes, I ran it using the updated file on my machine and it worked.

**Comment by kelvl** [comment]
:+1:

**Comment by vinluvie** [comment]
👍

**Pull request merged**
